title: Taufique Sekh # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>Data Scientist with 4+ years of commercial experience in analytics, strategy and sales and a master's degree in Data Science from NIIT University. Previously at Bandhan Bank.<br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/taufiquesekh/">View My LinkedIn Profile</a> 
  <a href="https://github.com/TaufiqueSekh">View My GitHub Profile</a> 

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
